language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate
  - COMPOSER_ROOT_VERSION=dev-master composer update --no-interaction --prefer-dist
  - COMPOSER_ROOT_VERSION=dev-master composer require --dev codeclimate/php-test-reporter:dev-master

script:
  - ./vendor/phpunit/phpunit/phpunit -v --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=7626c1d62b1c9ee7eadc4a337622bf4719d90fca9039bcf41cf6c00ba8a78d7f ./vendor/bin/test-reporter